### ISSUE TITLE
[CS230] Recurrent Neural Networks translation

### ISSUE THREAD

**Issue by erfannoury** [erfannoury/cheatsheet-translation#10]
The English version of the document can be found [here](https://stanford.edu/~shervine/teaching/cs-230/cheatsheet-recurrent-neural-networks).
To translate it to Persian, edit [this file](https://github.com/erfannoury/cheatsheet-translation/blob/master/fa/recurrent-neural-networks.md) and submit a PR here. Be sure to comment on this issue if you plan to do the translation (to prevent duplicate works).

**Comment by AlisterTA** [comment]
I do this one as well.any comments are welcomed and appreciated.

**Comment by AlisterTA** [comment]
Done  [link](https://github.com/shervinea/cheatsheet-translation/pull/126)

**Comment by erfannoury** [comment]
https://github.com/shervinea/cheatsheet-translation/pull/126 closes this.
