### ISSUE TITLE
[CS230] Deep Learning Tips and Tricks translation

### ISSUE THREAD

**Issue by erfannoury** [erfannoury/cheatsheet-translation#11]
The English version of the document can be found [here](https://stanford.edu/~shervine/teaching/cs-230/cheatsheet-deep-learning-tips-and-tricks).
To translate it to Persian, edit [this file](https://github.com/erfannoury/cheatsheet-translation/blob/master/fa/deep-learning-tips-and-tricks.md) and submit a PR here. Be sure to comment on this issue if you plan to do the translation (to prevent duplicate works).

**Comment by AlisterTA** [comment]
I'm halfway through doing this. any comments are welcomed and appreciated.

**Comment by AlisterTA** [comment]
Done. [reviewer wanted]

**Comment by erfannoury** [comment]
Did you submit the PR to the original repo or are planning to submit it to this repo?

**Comment by AlisterTA** [comment]
No I didn't, could you take care of that?

**Comment by erfannoury** [comment]
Yeah, I can submit it to the original repo, but where can I see your translation? You haven't submitted a PR (to this repo) yet.

**Comment by AlisterTA** [comment]
I just submitted a PR to the original repository. [here](https://github.com/shervinea/cheatsheet-translation/pull/125).

**Comment by erfannoury** [comment]
OK, I'll review it there.

**Comment by erfannoury** [comment]
https://github.com/shervinea/cheatsheet-translation/pull/125 closes this.
