### ISSUE TITLE
[CS230] Convolutional Neural Networks translation

### ISSUE THREAD

**Issue by erfannoury** [erfannoury/cheatsheet-translation#9]
The English version of the document can be found [here](https://stanford.edu/~shervine/teaching/cs-230/cheatsheet-convolutional-neural-networks). 
To translate it to Persian, edit [this file](https://github.com/erfannoury/cheatsheet-translation/blob/master/fa/convolutional-neural-networks.md) and submit a PR here. Be sure to comment on this issue if you plan to do the translation (to prevent duplicate works).

**Comment by ehsanmk** [comment]
I'm start this section.

**Comment by ehsanmk** [comment]
Done.
Please review and correct my mistake.

**Comment by erfannoury** [comment]
@ehsanmk where can I find your translation? Have you submitted a PR to the main repo?

**Comment by ehsanmk** [comment]
This is my  translation link. [https://github.com/ehsanmk/cheatsheet-translation/commit/91e7db19dfd8db7fc9086da0c4e96037e9b7f5f5?diff=unified](url)

**Comment by ehsanmk** [comment]
cheatsheet-translation/fa/convolutional-neural-networks.md

**Comment by ehsanmk** [comment]
This is the link of translation.  https://github.com/ehsanmk/cheatsheet-translation/commit/91e7db19dfd8db7fc9086da0c4e96037e9b7f5f5#diff-679a17d69582828c34ed947de9a37eaf

**Comment by erfannoury** [comment]
I think it would be faster if you create a PR to the main repo and then I can review it there. Thank you very much for your effort :)

**Comment by ehsanmk** [comment]
Done. Thank you.
https://github.com/shervinea/cheatsheet-translation/pull/127

**Comment by AlisterTA** [comment]
@erfannoury please review [this one](https://github.com/shervinea/cheatsheet-translation/pull/129/files)  when you have time

**Comment by erfannoury** [comment]
https://github.com/shervinea/cheatsheet-translation/pull/129.
